services:
  mongo:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - webdiaries-net

  blog-service:
    build:
      context: ./blog-service
      target: development
    ports:
      - "${BLOG_SERVICE_PORT}:${BLOG_SERVICE_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_AUTH_SOURCE=${MONGODB_AUTH_SOURCE}
      - BLOG_SERVICE_PORT=${BLOG_SERVICE_PORT}
      - NODE_ENV=development
      - SERVER_IP=127.0.0.1
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./blog-service:/app
    dns: 127.0.0.1
    networks:
      - webdiaries-net

  user-dashboard:
    build:
      context: ./user-dashboard
      target: development
    ports:
      - "${VITE_USER_DASHBOARD_PORT}:${VITE_USER_DASHBOARD_PORT}"
    environment:
      - VITE_BACKEND_API=${VITE_BACKEND_API}
      - VITE_USER_DASHBOARD_PORT=${VITE_USER_DASHBOARD_PORT}
      - NODE_ENV=development
    volumes:
      - ./user-dashboard:/app
      - /app/node_modules
    dns: 127.0.0.1
    networks:
      - webdiaries-net

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "${VITE_FRONTEND_PORT}:${VITE_FRONTEND_PORT}"
    environment:
      - VITE_BACKEND_API=${VITE_BACKEND_API}
      - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT}
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    dns: 127.0.0.1
    networks:
      - webdiaries-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - blog-service
      - user-dashboard
      - frontend
    dns: 127.0.0.1
    restart: unless-stopped
    networks:
      - webdiaries-net

  dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

networks:
  webdiaries-net:
    driver: bridge

volumes:
  mongo-data:
