name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/webdiaries.online
            git pull origin main
            echo "${{ secrets.PROD_ENV }}" > .env.production.local
            bash prod-envsubst.sh
            docker compose --env-file .env.production.local -f 'prod.compose.yml' up -d --build
